# Generated by Django 2.2.11 on 2021-01-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name="Contact's email (optional)"),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=256, verbose_name='Name of contact (optional)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name="Contact's mobile phone number (optional)"),
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name="Contact's role (optional)"),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name="Contact's email (optional)"),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='name',
            field=models.CharField(blank=True, max_length=256, verbose_name='Name of contact (optional)'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name="Contact's mobile phone number (optional)"),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='role',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name="Contact's role (optional)"),
        ),
    ]
