# Generated by Django 2.2.11 on 2021-02-08 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_auto_20210205_1339"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="contact",
            managers=[],
        ),
    ]
