# Generated by Django 2.2.20 on 2021-05-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20210208_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name="Contact's role (optional)"),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='role',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name="Contact's role (optional)"),
        ),
    ]
