# Generated by Django 2.2.11 on 2021-02-16 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stakeholder", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalstakeholder",
            name="country",
        ),
        migrations.RemoveField(
            model_name="stakeholder",
            name="country",
        ),
    ]
