# Generated by Django 2.2.11 on 2021-01-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stakeholder", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstakeholder",
            name="type",
            field=models.CharField(
                choices=[
                    (
                        "PROFESSIONAL",
                        "Royal College or other professional organisation",
                    ),
                    ("ACADEMIC", "Academic/research organisation"),
                    ("PATIENT_GROUP", "Patient group/voluntary sector"),
                    ("INDIVIDUAL", "Individual"),
                    ("COMMERCIAL", "Commercial organisation"),
                    ("OTHER", "Other"),
                ],
                max_length=13,
                verbose_name="stakeholder type",
            ),
        ),
        migrations.AlterField(
            model_name="stakeholder",
            name="type",
            field=models.CharField(
                choices=[
                    (
                        "PROFESSIONAL",
                        "Royal College or other professional organisation",
                    ),
                    ("ACADEMIC", "Academic/research organisation"),
                    ("PATIENT_GROUP", "Patient group/voluntary sector"),
                    ("INDIVIDUAL", "Individual"),
                    ("COMMERCIAL", "Commercial organisation"),
                    ("OTHER", "Other"),
                ],
                max_length=13,
                verbose_name="stakeholder type",
            ),
        ),
    ]
