# Generated by Django 2.2.11 on 2021-01-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0002_auto_20210126_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstakeholder',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Should this organisation be published on the condition pages'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Should this organisation be published on the condition pages'),
        ),
    ]
