# Generated by Django 2.2.11 on 2021-02-17 09:06

from django.db import migrations, models
import nsc.stakeholder.models


class Migration(migrations.Migration):

    dependencies = [
        ("stakeholder", "0002_auto_20210216_1719"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstakeholder",
            name="countries",
            field=nsc.stakeholder.models.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("ENGLAND", "England"),
                        ("NORTHERN_IRELAND", "Northern Ireland"),
                        ("SCOTLAND", "Scotland"),
                        ("WALES", "Wales"),
                        ("UK", "UK"),
                        ("INTERNATIONAL", "International"),
                    ],
                    max_length=16,
                ),
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="stakeholder",
            name="countries",
            field=nsc.stakeholder.models.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("ENGLAND", "England"),
                        ("NORTHERN_IRELAND", "Northern Ireland"),
                        ("SCOTLAND", "Scotland"),
                        ("WALES", "Wales"),
                        ("UK", "UK"),
                        ("INTERNATIONAL", "International"),
                    ],
                    max_length=16,
                ),
                null=True,
                size=None,
            ),
        ),
    ]
