# Generated by Django 4.2.20 on 2025-05-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholder', '0004_auto_20210511_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalstakeholder',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical stakeholder', 'verbose_name_plural': 'historical stakeholders'},
        ),
        migrations.AlterField(
            model_name='historicalstakeholder',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
