# Generated by Django 2.2.9 on 2020-02-27 12:01

from django.db import migrations, models
import nsc.document.models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicaldocument", old_name="document", new_name="upload",
        ),
        migrations.RemoveField(model_name="document", name="document",),
        migrations.AddField(
            model_name="document",
            name="upload",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=nsc.document.models.review_document_path,
                verbose_name="document",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("supporting", "Supporting documents"),
                    ("external", "External Review"),
                    ("recommendation", "Review recommendation"),
                ],
                max_length=256,
                verbose_name="type of document",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("supporting", "Supporting documents"),
                    ("external", "External Review"),
                    ("recommendation", "Review recommendation"),
                ],
                max_length=256,
                verbose_name="type of document",
            ),
        ),
    ]
