# Generated by Django 2.2.9 on 2020-03-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("document", "0002_auto_20200227_1201")]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("coversheet", "Coversheet"),
                    ("submission_form", "Submission form"),
                    ("evidence_review", "Evidence Review"),
                    ("recommendation", "Review recommendation"),
                ],
                max_length=256,
                verbose_name="type of document",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("coversheet", "Coversheet"),
                    ("submission_form", "Submission form"),
                    ("evidence_review", "Evidence Review"),
                    ("recommendation", "Review recommendation"),
                ],
                max_length=256,
                verbose_name="type of document",
            ),
        ),
    ]
