# Generated by Django 2.2.11 on 2021-02-12 17:02

from django.db import migrations, models
import nsc.document.models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0003_auto_20210211_1407"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="upload",
            field=models.FileField(
                max_length=256,
                upload_to=nsc.document.models.document_path,
                verbose_name="upload",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldocument",
            name="upload",
            field=models.TextField(max_length=256, verbose_name="upload"),
        ),
    ]
