# Generated by Django 5.0.3 on 2025-06-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0010_alter_document_policies"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="uuid",
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="historicaldocument",
            name="uuid",
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
    ]
