# Generated by Django 2.2.11 on 2021-02-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0003_auto_20210211_1407"),
        ("document", "0002_auto_20210211_1014"),
    ]

    operations = []
