# Generated by Django 5.0.3 on 2025-06-02 12:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0010_alter_document_policies"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AddField(
            model_name="historicaldocument",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
