# Generated by Django 2.2.9 on 2020-03-13 11:36

from django.db import migrations, models
import nsc.document.models


class Migration(migrations.Migration):

    dependencies = [("document", "0003_auto_20200304_1143")]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="upload",
            field=models.FileField(
                upload_to=nsc.document.models.review_document_path,
                verbose_name="upload",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldocument",
            name="upload",
            field=models.TextField(max_length=100, verbose_name="upload"),
        ),
    ]
