# Generated by Django 5.0.3 on 2025-06-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0004_document_uuid_historicaldocument_uuid"),
    ]

    operations = [
        migrations.RunSQL(
            """
            UPDATE document_document
            SET uuid = gen_random_uuid()
            WHERE uuid IS NULL;
            """
        ),
    ]
