# Generated by Django 5.0.3 on 2025-06-02 18:47

# 0005_populate_uuids.py
import uuid
from django.db import migrations


def gen_uuids(apps, schema_editor):
    Document = apps.get_model("document", "Document")
    for doc in Document.objects.all():
        if not doc.uuid:
            doc.uuid = uuid.uuid4()
            doc.save(update_fields=["uuid"])


def gen_historical_uuids(apps, schema_editor):
    HistoricalDocument = apps.get_model("document", "HistoricalDocument")
    for doc in HistoricalDocument.objects.all():
        if not doc.uuid:
            doc.uuid = uuid.uuid4()
            doc.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0004_document_uuid_historicaldocument_uuid"),
    ]

    operations = [
        migrations.RunPython(gen_uuids, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(
            gen_historical_uuids, reverse_code=migrations.RunPython.noop
        ),
    ]
