# Generated by Django 2.2.9 on 2020-03-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("document", "0004_auto_20200313_1136")]

    operations = [
        migrations.RemoveField(model_name="document", name="is_public"),
        migrations.RemoveField(model_name="historicaldocument", name="is_public"),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("cover_sheet", "Coversheet"),
                    ("submission_form", "Submission form"),
                    ("evidence_review", "Evidence review"),
                    ("external_review", "External review"),
                ],
                max_length=256,
                verbose_name="type of document",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("cover_sheet", "Coversheet"),
                    ("submission_form", "Submission form"),
                    ("evidence_review", "Evidence review"),
                    ("external_review", "External review"),
                ],
                max_length=256,
                verbose_name="type of document",
            ),
        ),
    ]
