# Generated by Django 2.2.11 on 2021-02-12 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0005_auto_20210212_0911"),
        ("document", "0004_auto_20210212_1702"),
    ]

    operations = []
