# Generated by Django 5.0.3 on 2025-06-02 18:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0005_populate_unique_uuids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="historicaldocument",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
