# Generated by Django 5.0.14 on 2026-03-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0006_alter_document_uuid_alter_historicaldocument_uuid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicaldocument",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical document",
                "verbose_name_plural": "historical documents",
            },
        ),
        migrations.AlterField(
            model_name="historicaldocument",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
