# Generated by Django 2.2.20 on 2021-04-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0008_auto_20210422_1416"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentpolicy",
            options={"get_latest_by": "modified"},
        ),
    ]
