# Generated by Django 4.2.20 on 2025-05-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_alter_document_policies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaldocument',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical document', 'verbose_name_plural': 'historical documents'},
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
