# Generated by Django 2.2.20 on 2021-04-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_session_id",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
    ]
