# Generated by Django 2.2.11 on 2021-02-05 13:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("notify_id", models.CharField(max_length=50)),
                ("address", models.EmailField(max_length=254)),
                ("template_id", models.CharField(max_length=50)),
                (
                    "context",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sending", "Sending"),
                            (
                                "permanent-failure",
                                "permanent_failure",
                                "Permanent Failure",
                            ),
                            (
                                "temporary-failure",
                                "temporary_failure",
                                "Temporary Failure",
                            ),
                            (
                                "technical-failure",
                                "technical_failure",
                                "Technical Failure",
                            ),
                        ],
                        default="pending",
                        max_length=17,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ("-modified", "-created"),
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
