# Generated by Django 2.2.11 on 2021-02-08 16:11

from django.db import migrations
import nsc.notify.models


def create_notify_receipt_token(apps, schema_editor):
    Token = apps.get_model("notify", "ReceiptUserToken")
    t = Token.objects.create(token=nsc.notify.models.generate_token())


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0002_auto_20210208_1611"),
    ]

    operations = [migrations.RunPython(create_notify_receipt_token)]
