# Generated by Django 2.2.20 on 2021-04-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0003_auto_20210208_1611"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="email",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="receiptusertoken",
            options={"get_latest_by": "modified"},
        ),
    ]
