# Generated by Django 2.2.20 on 2021-04-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0005_auto_20210430_1135"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="notify_id",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=50
            ),
        ),
    ]
