# Generated by Django 5.0.14 on 2025-08-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0006_auto_20210430_1225"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="context",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="email",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("created", "Created"),
                    ("sending", "Sending"),
                    ("delivered", "Delivered"),
                    ("permanent-failure", "Permanent Failure"),
                    ("temporary-failure", "Temporary Failure"),
                    ("technical-failure", "Technical Failure"),
                    ("too-many-attempts", "Gave up after too many attempts"),
                ],
                default="pending",
                max_length=17,
            ),
        ),
    ]
