# Generated by Django 5.1 on 2025-04-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0006_auto_20210430_1225"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="context",
            field=models.JSONField(default=dict),
        ),
    ]
