# Generated by Django 4.2.20 on 2025-05-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0006_auto_20210430_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='context',
            field=models.JSONField(default=dict),
        ),
    ]
