# Generated by Django 5.2.12 on 2026-04-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0007_alter_email_context_alter_email_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='one_click_unsubscribe_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
