# Generated by Django 2.2.20 on 2021-04-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0002_stakeholdersubscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stakeholdersubscription",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={"get_latest_by": "modified"},
        ),
    ]
