# Generated by Django 2.2.9 on 2020-02-19 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("policy", "0002_auto_20200206_1043"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(max_length=256, unique=True, verbose_name="slug"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Due to be reviewed"),
                            ("pre_consultation", "Pre-consultation"),
                            ("consultation", "Consultation"),
                            ("post_consultation", "Post consultation"),
                            ("completed", "Completed"),
                        ],
                        default="pre_consultation",
                        max_length=50,
                        verbose_name="status",
                    ),
                ),
                (
                    "review_type",
                    models.CharField(
                        choices=[("rapid", "Rapid review"), ("other", "Other")],
                        max_length=50,
                        verbose_name="type of review",
                    ),
                ),
                (
                    "consultation_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="consultation start date"
                    ),
                ),
                (
                    "consultation_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="consultation end date"
                    ),
                ),
                (
                    "review_date",
                    models.DateField(blank=True, null=True, verbose_name="review date"),
                ),
                (
                    "recommendation",
                    models.NullBooleanField(
                        default=None, verbose_name="recommendation"
                    ),
                ),
                ("summary", models.TextField(verbose_name="summary")),
                ("summary_html", models.TextField(verbose_name="HTML summary")),
                (
                    "policies",
                    models.ManyToManyField(
                        related_name="reviews",
                        to="policy.Policy",
                        verbose_name="policies",
                    ),
                ),
            ],
            options={"verbose_name_plural": "reviews", "ordering": ("name", "pk"),},
        ),
        migrations.CreateModel(
            name="HistoricalReview",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="name")),
                ("slug", models.SlugField(max_length=256, verbose_name="slug")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Due to be reviewed"),
                            ("pre_consultation", "Pre-consultation"),
                            ("consultation", "Consultation"),
                            ("post_consultation", "Post consultation"),
                            ("completed", "Completed"),
                        ],
                        default="pre_consultation",
                        max_length=50,
                        verbose_name="status",
                    ),
                ),
                (
                    "review_type",
                    models.CharField(
                        choices=[("rapid", "Rapid review"), ("other", "Other")],
                        max_length=50,
                        verbose_name="type of review",
                    ),
                ),
                (
                    "consultation_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="consultation start date"
                    ),
                ),
                (
                    "consultation_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="consultation end date"
                    ),
                ),
                (
                    "review_date",
                    models.DateField(blank=True, null=True, verbose_name="review date"),
                ),
                (
                    "recommendation",
                    models.NullBooleanField(
                        default=None, verbose_name="recommendation"
                    ),
                ),
                ("summary", models.TextField(verbose_name="summary")),
                ("summary_html", models.TextField(verbose_name="HTML summary")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical review",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
