# Generated by Django 2.2.11 on 2021-01-29 13:51

from django.db import migrations
import nsc.review.models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreview',
            name='review_type',
            field=nsc.review.models.MultipleTypeField(choices=[('evidence', 'Evidence review'), ('map', 'Evidence map'), ('cost', 'Cost-effective model'), ('disease', 'Disease model'), ('systematic', 'Systematic review'), ('meta', 'Systematic review and meta analysis'), ('other', 'Other')], max_length=50, verbose_name='type of review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_type',
            field=nsc.review.models.MultipleTypeField(choices=[('evidence', 'Evidence review'), ('map', 'Evidence map'), ('cost', 'Cost-effective model'), ('disease', 'Disease model'), ('systematic', 'Systematic review'), ('meta', 'Systematic review and meta analysis'), ('other', 'Other')], max_length=50, verbose_name='type of review'),
        ),
    ]
