# Generated by Django 2.2.11 on 2021-02-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stakeholder", "0001_initial"),
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="stakeholders",
            field=models.ManyToManyField(
                related_name="reviews", to="stakeholder.Stakeholder"
            ),
        ),
    ]
