# Generated by Django 2.2.9 on 2020-02-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("review", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="historicalreview", name="review_date"),
        migrations.RemoveField(model_name="review", name="review_date"),
        migrations.AddField(
            model_name="historicalreview",
            name="discussion_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="discussion date"
            ),
        ),
        migrations.AddField(
            model_name="historicalreview",
            name="phase",
            field=models.CharField(
                choices=[
                    ("pre_consultation", "Pre-consultation"),
                    ("consultation", "Consultation"),
                    ("post_consultation", "Post consultation"),
                    ("completed", "Completed"),
                ],
                default="pre_consultation",
                max_length=50,
                verbose_name="review phase",
            ),
        ),
        migrations.AddField(
            model_name="historicalreview",
            name="review_end",
            field=models.DateField(
                blank=True, null=True, verbose_name="review end date"
            ),
        ),
        migrations.AddField(
            model_name="historicalreview",
            name="review_start",
            field=models.DateField(
                blank=True, null=True, verbose_name="review start date"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="discussion_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="discussion date"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="phase",
            field=models.CharField(
                choices=[
                    ("pre_consultation", "Pre-consultation"),
                    ("consultation", "Consultation"),
                    ("post_consultation", "Post consultation"),
                    ("completed", "Completed"),
                ],
                default="pre_consultation",
                max_length=50,
                verbose_name="review phase",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="review_end",
            field=models.DateField(
                blank=True, null=True, verbose_name="review end date"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="review_start",
            field=models.DateField(
                blank=True, null=True, verbose_name="review start date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalreview",
            name="recommendation",
            field=models.BooleanField(default=False, verbose_name="recommendation"),
        ),
        migrations.AlterField(
            model_name="historicalreview",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=50,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="recommendation",
            field=models.BooleanField(default=False, verbose_name="recommendation"),
        ),
        migrations.AlterField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=50,
                verbose_name="status",
            ),
        ),
    ]
