# Generated by Django 2.2.9 on 2020-03-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("review", "0002_auto_20200228_0902")]

    operations = [migrations.RemoveField(model_name="review", name="policies")]
