# Generated by Django 2.2.11 on 2021-02-01 14:26
from django.db import migrations


def set_stakeholders_from_policies(apps, schema_editor):
    Review = apps.get_model("review", "Review")
    Stakeholder = apps.get_model("stakeholder", "Stakeholder")

    for review in Review.objects.all():
        policy_ids = review.policies.values_list("id", flat=True)
        review.stakeholders.set(Stakeholder.objects.filter(policies__pk__in=policy_ids).distinct())


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_stakeholders'),
        ('stakeholder', '0001_initial')
    ]

    operations = [
        migrations.RunPython(set_stakeholders_from_policies),
    ]
