# Generated by Django 2.2.9 on 2020-03-11 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("review", "0003_auto_20200310_1513")]

    operations = [
        migrations.RemoveField(model_name="review", name="phase"),
        migrations.RemoveField(model_name="historicalreview", name="phase"),
    ]
