# Generated by Django 2.2.11 on 2021-02-02 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_reviewnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewnotification',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='review.Review'),
        ),
        migrations.AlterField(
            model_name='reviewnotification',
            name='stakeholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='stakeholder.Stakeholder'),
        ),
        migrations.AlterField(
            model_name='reviewnotification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent')], default='PENDING', max_length=7),
        ),
    ]
