# Generated by Django 2.2.9 on 2020-03-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_remove_review_policies'),
        ('review', '0004_auto_20200311_1249'),
    ]

    operations = [
    ]
