# Generated by Django 2.2.9 on 2020-03-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0005_merge_20200311_1614"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalreview",
            name="review_type",
            field=models.CharField(
                choices=[
                    ("evidence", "Evidence review"),
                    ("map", "Evidence map"),
                    ("cost", "Cost-effective model"),
                    ("systematic", "Systematic review"),
                ],
                max_length=50,
                verbose_name="type of review",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="review_type",
            field=models.CharField(
                choices=[
                    ("evidence", "Evidence review"),
                    ("map", "Evidence map"),
                    ("cost", "Cost-effective model"),
                    ("systematic", "Systematic review"),
                ],
                max_length=50,
                verbose_name="type of review",
            ),
        ),
    ]
