# Generated by Django 2.2.9 on 2020-03-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("review", "0006_auto_20200312_1732")]

    operations = [
        migrations.AlterField(
            model_name="historicalreview",
            name="recommendation",
            field=models.NullBooleanField(verbose_name="recommendation"),
        ),
        migrations.AlterField(
            model_name="review",
            name="recommendation",
            field=models.NullBooleanField(verbose_name="recommendation"),
        ),
    ]
