# Generated by Django 2.2.9 on 2020-03-18 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("review", "0007_auto_20200316_1514")]

    operations = [
        migrations.RemoveField(model_name="historicalreview", name="status"),
        migrations.RemoveField(model_name="review", name="status"),
    ]
