# Generated by Django 2.2.9 on 2020-03-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("review", "0008_auto_20200318_1128")]

    operations = [
        migrations.AddField(
            model_name="historicalreview",
            name="background",
            field=models.TextField(default="", verbose_name="history"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalreview",
            name="background_html",
            field=models.TextField(default="", verbose_name="HTML history"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="background",
            field=models.TextField(default="", verbose_name="history"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="background_html",
            field=models.TextField(default="", verbose_name="HTML history"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalreview",
            name="review_type",
            field=models.CharField(
                choices=[
                    ("evidence", "Evidence review"),
                    ("map", "Evidence map"),
                    ("cost", "Cost-effective model"),
                    ("disease", "Disease model"),
                    ("systematic", "Systematic review"),
                    ("meta", "Systematic review and meta analysis"),
                    ("other", "Other"),
                ],
                max_length=50,
                verbose_name="type of review",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="review_type",
            field=models.CharField(
                choices=[
                    ("evidence", "Evidence review"),
                    ("map", "Evidence map"),
                    ("cost", "Cost-effective model"),
                    ("disease", "Disease model"),
                    ("systematic", "Systematic review"),
                    ("meta", "Systematic review and meta analysis"),
                    ("other", "Other"),
                ],
                max_length=50,
                verbose_name="type of review",
            ),
        ),
    ]
