# Generated by Django 2.2.11 on 2021-02-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0011_summarydraft"),
    ]

    operations = [
        migrations.AddField(
            model_name="summarydraft",
            name="updated",
            field=models.BooleanField(default=False),
        ),
    ]
