# Generated by Django 2.2.11 on 2021-02-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_summarydraft_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreview',
            name='published',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='review',
            name='published',
            field=models.NullBooleanField(),
        ),
    ]
