# Generated by Django 2.2.11 on 2021-02-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0003_auto_20210208_1611"),
        ("review", "0013_auto_20210211_1532"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="decision_published_notifications",
            field=models.ManyToManyField(
                related_name="publish_notification_reviews", to="notify.Email"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="open_consultation_notifications",
            field=models.ManyToManyField(
                related_name="open_consultation_reviews", to="notify.Email"
            ),
        ),
    ]
