# Generated by Django 2.2.11 on 2021-02-12 11:13

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("policy", "0001_initial"),
        ("review", "0014_auto_20210211_1751"),
    ]

    operations = [
        migrations.AlterModelOptions(name="summarydraft", options={},),
        migrations.AlterUniqueTogether(
            name="summarydraft", unique_together={("policy", "review")},
        ),
        migrations.CreateModel(
            name="ReviewRecommendation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("recommendation", models.NullBooleanField()),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_recomendations",
                        to="policy.Policy",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_recomendations",
                        to="review.Review",
                    ),
                ),
            ],
            options={"unique_together": {("policy", "review")},},
        ),
    ]
