# Generated by Django 2.2.11 on 2021-02-12 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0015_auto_20210212_1113"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalreview",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="historicalreview",
            name="slug",
            field=models.SlugField(max_length=100, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="review",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="review",
            name="slug",
            field=models.SlugField(max_length=100, unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="reviewrecommendation",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_recommendations",
                to="policy.Policy",
            ),
        ),
        migrations.AlterField(
            model_name="reviewrecommendation",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_recommendations",
                to="review.Review",
            ),
        ),
    ]
