# Generated by Django 2.2.11 on 2021-02-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0016_auto_20210212_1658"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalreview",
            name="recommendation",
        ),
        migrations.RemoveField(
            model_name="review",
            name="recommendation",
        ),
    ]
