# Generated by Django 2.2.11 on 2021-02-16 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0017_auto_20210215_1457"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ("name", "pk"),
                "permissions": [("evidence_review_manager", "Evidence Review Manager")],
                "verbose_name_plural": "reviews",
            },
        ),
    ]
