# Generated by Django 5.1 on 2025-04-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0021_auto_20210323_1518"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalreview",
            name="published",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="published",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reviewrecommendation",
            name="recommendation",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
