# Generated by Django 5.0.14 on 2026-03-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0021_auto_20210323_1518"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalreview",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical review",
                "verbose_name_plural": "historical reviews",
            },
        ),
        migrations.AlterField(
            model_name="historicalreview",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalreview",
            name="published",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="published",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reviewrecommendation",
            name="recommendation",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
