# Generated by Django 2.2.11 on 2021-02-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpolicy',
            name='archived',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalpolicy',
            name='archived_reason',
            field=models.TextField(blank=True, verbose_name='Archived Reason'),
        ),
        migrations.AddField(
            model_name='historicalpolicy',
            name='archived_reason_html',
            field=models.TextField(blank=True, verbose_name='HTML Archived Reason'),
        ),
        migrations.AddField(
            model_name='policy',
            name='archived',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='archived_reason',
            field=models.TextField(blank=True, verbose_name='Archived Reason'),
        ),
        migrations.AddField(
            model_name='policy',
            name='archived_reason_html',
            field=models.TextField(blank=True, verbose_name='HTML Archived Reason'),
        ),
    ]
