# Generated by Django 2.2.9 on 2020-02-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("policy", "0001_initial")]

    operations = [
        migrations.RenameField(
            model_name="historicalpolicy",
            old_name="description",
            new_name="description_html",
        ),
        migrations.RenameField(
            model_name="historicalpolicy", old_name="markup", new_name="description"
        ),
        migrations.RenameField(
            model_name="policy", old_name="description", new_name="description_html"
        ),
        migrations.RenameField(
            model_name="policy", old_name="markup", new_name="description"
        ),
    ]
