# Generated by Django 2.2.9 on 2020-02-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("policy", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="historicalpolicy",
            name="last_review",
            field=models.DateField(blank=True, null=True, verbose_name="last review"),
        ),
        migrations.AddField(
            model_name="historicalpolicy",
            name="next_review",
            field=models.DateField(blank=True, null=True, verbose_name="next review"),
        ),
        migrations.AddField(
            model_name="policy",
            name="last_review",
            field=models.DateField(blank=True, null=True, verbose_name="last review"),
        ),
        migrations.AddField(
            model_name="policy",
            name="next_review",
            field=models.DateField(blank=True, null=True, verbose_name="next review"),
        ),
    ]
