# Generated by Django 2.2.11 on 2021-02-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpolicy",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="historicalpolicy",
            name="slug",
            field=models.SlugField(max_length=100, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="policy",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="policy",
            name="slug",
            field=models.SlugField(max_length=100, unique=True, verbose_name="slug"),
        ),
    ]
