# Generated by Django 2.2.11 on 2021-02-12 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("policy", "0002_auto_20210212_1644"),
        ("policy", "0002_auto_20210211_1104"),
    ]

    operations = []
