# Generated by Django 2.2.11 on 2021-02-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_merge_20210212_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpolicy',
            name='last_review',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='last_review',
        ),
        migrations.AddField(
            model_name='historicalpolicy',
            name='legacy_last_review',
            field=models.DateField(blank=True, help_text='Populated via scrape, used when no reviews are completed via this app.', null=True, verbose_name='last review'),
        ),
        migrations.AddField(
            model_name='policy',
            name='legacy_last_review',
            field=models.DateField(blank=True, help_text='Populated via scrape, used when no reviews are completed via this app.', null=True, verbose_name='last review'),
        ),
    ]
