# Generated by Django 2.2.9 on 2020-03-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("policy", "0003_auto_20200226_1153"),
        ("policy", "0003_auto_20200227_1603"),
    ]

    operations = []
