# Generated by Django 2.2.9 on 2020-03-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("policy", "0005_policy_reviews")]

    operations = [
        migrations.AddField(
            model_name="historicalpolicy",
            name="background",
            field=models.TextField(default="", verbose_name="summary"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalpolicy",
            name="background_html",
            field=models.TextField(default="", verbose_name="HTML summary"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="policy",
            name="background",
            field=models.TextField(default="", verbose_name="summary"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="policy",
            name="background_html",
            field=models.TextField(default="", verbose_name="HTML summary"),
            preserve_default=False,
        ),
    ]
