# Generated by Django 5.0.14 on 2025-05-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policy", "0006_auto_20210218_1210"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpolicy",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="legacy URL"),
        ),
        migrations.AddField(
            model_name="policy",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="legacy URL"),
        ),
        migrations.AlterField(
            model_name="historicalpolicy",
            name="recommendation",
            field=models.BooleanField(
                blank=True, default=None, null=True, verbose_name="recommendation"
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="recommendation",
            field=models.BooleanField(
                blank=True, default=None, null=True, verbose_name="recommendation"
            ),
        ),
    ]
