# Generated by Django 5.1 on 2025-04-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policy", "0006_auto_20210218_1210"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpolicy",
            name="recommendation",
            field=models.BooleanField(
                blank=True, default=None, null=True, verbose_name="recommendation"
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="recommendation",
            field=models.BooleanField(
                blank=True, default=None, null=True, verbose_name="recommendation"
            ),
        ),
    ]
