# Generated by Django 4.2.20 on 2025-05-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0006_auto_20210218_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpolicy',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical policy', 'verbose_name_plural': 'historical policies'},
        ),
        migrations.AlterField(
            model_name='historicalpolicy',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpolicy',
            name='recommendation',
            field=models.BooleanField(default=None, null=True, verbose_name='recommendation'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='recommendation',
            field=models.BooleanField(default=None, null=True, verbose_name='recommendation'),
        ),
    ]
