# Generated by Django 5.0.14 on 2025-10-30 16:55

from django.db import migrations

def update_psychiatric_illness_policy(apps, schema_editor):
 
    Policy = apps.get_model("policy", "Policy")
    psychiatric_illness_policy = Policy.objects.get(slug="psychiatric-illness")
    psychiatric_illness_policy.name = "Antenatal and postnatal mental health"
    psychiatric_illness_policy.slug = "antenatal-and-postnatal-mental-health"
    psychiatric_illness_policy.save()

class Migration(migrations.Migration):

    dependencies = [
        ("policy", "0007_alter_historicalpolicy_recommendation_and_more"),
    ]

    operations = [
        migrations.RunPython(update_psychiatric_illness_policy),
    ]