# Generated by Django 5.0.14 on 2026-03-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policy", "0008_auto_20251030_1655"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalpolicy",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical policy",
                "verbose_name_plural": "historical policies",
            },
        ),
        migrations.AlterField(
            model_name="historicalpolicy",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
